System:

  Security:

    dmUser:
      name:             User
      page:             true
      credentials:      security_user
      components:
        signin:
        form:           { name: "Register" }
        forgotPassword:
        dashboard:
        info:

Content:

  Forum:

    board:
      model:                  DmForumBoard
      name:                   Board|Board
      page:                   true
      components:
        list:

    forum:
      model:                  DmForumForum
      name:                   Forum
      page:                   true
      parent:                 board
      components:
        listByCategory:
          filters:            [ board ]

    moderator:
      model:                  DmForumModerator
      name:                   Moderator
      parent:                 Forum

    topic:
      model:                  DmForumTopic
      name:                   Topic
      page:                   true
      parent:                 forum
      components:
        listByForum:
          filters:            [ forum ]
        show:
        form:

    post:
      model:                  DmForumPost
      name:                   Post
      components:
        list:
        listByTopic:
          filters:            [ topic ]
        show:
        form: