<?php

/**
 * PluginDmForumTopicTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmForumTopicTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmForumTopicTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmForumTopic');
    }
}