<?php

/**
 * PluginDmForumForumModeratorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmForumForumModeratorTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmForumForumModeratorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmForumForumModerator');
    }
}