<?php

/**
 * PluginDmForumForumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmForumForumTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmForumForumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmForumForum');
    }
}