<?php

/**
 * PluginDmForumBoard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmForumBoard extends BaseDmForumBoard
{
  public function getPosts() {
    return $this->getPostsQuery()->execute();
  }

  public function getNbPosts() {
    return $this->getPostsQuery()->count();
  }

  public function getLastPost() {
    return $this->getPostsQuery()
      ->orderBy('fp.updated_at DESC')
      ->fetchOne()
      ;
  }
  
  public function getPostsQuery() {
    $query = Doctrine_Core::getTable('DmForumPost')
      ->createQuery('fp')
      ->leftJoin('fp.Topic ft')
      ->leftJoin('ft.Forum ff')
      ->where('fp.is_active = ?', true)
      ->where('fp.is_approved = ?', true)
      ->andWhere('ft.is_active = ?', true)
      ->andWhere('ft.is_approved = ?', true)
      ->andWhere('ff.is_active = ?', true)
      ->andWhere('ff.is_approved = ?', true)
      ->addWhere('ff.board_id = ?', $this->id)
      ;

    return $query;
  }
}