<?php

/**
 * PluginDmForumCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmForumCategoryTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmForumCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmForumCategory');
    }
}