<?php

/**
 * PluginDmForumForum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmForumForum extends BaseDmForumForum
{
  public function getTopics() {
      return $this->getTopicsQuery()->execute();
  }

  public function getPosts() {
    return $this->getPostsQuery()->execute()
    ;
  }

  public function getNbPosts() {
    return $this->getPostsQuery()->count();
  }

  public function getNbTopics() {
    return $this->getTopicsQuery()->count();
  }

  public function getNbUnapprovedTopics() {
    return $this->getTopicsQuery(false)->count();
  }

  public function getLastPost() {
    $query = $this->getPostsQuery();
    return $query->orderBy($query->getRootAlias().'.created_at')->fetchOne();
  }

  public function getPostsQuery($isApproved = true) {
    $query = Doctrine_Core::getTable('DmForumPost')->createQuery('fp');
    $query->leftJoin($query->getRootAlias().'.Topic ft')
          ->where($query->getRootAlias().'.is_active = ?', true)
          ->andWhere('ft.forum_id = ?', $this->id)
          ->andWhere('ft.is_active = ?', true)
          ->andWhere('ft.is_approved = ?', $isApproved)
          ->andWhere('fp.is_approved = ?', $isApproved);

    return $query;
  }

  public function getTopicsQuery($isApproved = true) {
      $query = Doctrine_Core::getTable('DmForumTopic')->createQuery('ft');
      $query->where($query->getRootAlias().'.is_active = ?', true)
            ->andWhere($query->getRootAlias().'.forum_id = ?', $this->id)
            ->andWhere($query->getRootAlias(). '.is_approved = ?', $isApproved);

      return $query;
  }

}