<?php

/**
 * PluginDmForumModeratorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmForumModeratorTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmForumModeratorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmForumModerator');
    }
}