<?php

/**
 * PluginDmForumPostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmForumPostTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmForumPostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmForumPost');
    }
}