<?php

/**
 * PluginDmForumForum
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmForumForum extends BaseDmForumForum
{
  public function getTopics() {
    return $this->getApprovedTopicsQuery()
      ->execute()
    ;
  }

  public function getPosts() {
    return $this->getApprovedPostsQuery()
      ->execute()
    ;
  }

  public function getNbPosts() {
    return $this->getApprovedPostsQuery()
      ->count()
    ;
  }

  public function getNbTopics() {
    return $this->getApprovedTopicsQuery()->count();
  }

  public function getNbUnapprovedTopics() {
    $query = $this->getTopicsQuery();
    return $query
      ->andWhere($query->getRootAlias().'.is_approved = ?', false)
      ->count();
  }

  public function getLastPost() {
    $query = $this->getApprovedPostsQuery();
    return $query
      ->orderBy($query->getRootAlias().'.updated_at')
      ->fetchOne()
    ;
  }

  public function getApprovedPostsQuery() {
    $query = $this->getPostsQuery();
    $query->andWhere($query->getRootAlias().'.is_approved = ?', true)
      ->andWhere('ft.is_approved = ?', true)
      ;

    return $query;
  }
  public function getPostsQuery(Doctrine_Query $query = null) {
    if (null === $query) {
      $query = Doctrine_Core::getTable('DmForumPost')
        ->createQuery('fp')
        ;
    }
    $query->leftJoin($query->getRootAlias().'.Topic ft')
      ->where($query->getRootAlias().'.is_active = ?', true)
      ->andWhere('ft.is_active = ?', true)
      ->andWhere('ft.forum_id = ?', $this->id)
      ;

    return $query;
  }

  public function getApprovedTopicsQuery() {
    $query = $this->getTopicsQuery();
    $query->where($query->getRootAlias().'.is_approved = ?', true)
      ;

    return $query;
  }

  public function getTopicsQuery(Doctrine_Query $query = null) {
    if (null === $query) {
      $query = Doctrine_Core::getTable('DmForumTopic')
        ->createQuery('ft')
        ;
    }
    $query->where($query->getRootAlias().'.is_active = ?', true)
      ->andWhere($query->getRootAlias().'.forum_id = ?', $this->id)
      ;

    return $query;
  }

}