<?php

/**
 * PluginDmForumCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmForumCategory extends BaseDmForumCategory
{
  public function getNbPosts() {
    return Doctrine::getTable('DmForumPost')
      ->createQuery('p')
      ->leftJoin('p.Topic t')
      ->leftJoin('t.Forum f')
      ->where('f.Category = ?', $this)
      ->count()
    ;
  }
}