<?php

/**
 * PluginDmForumTopic
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class PluginDmForumTopic extends BaseDmForumTopic
{
  public function getNbReplies() {
    return Doctrine::getTable('DmForumPost')
      ->createQuery('p')
      ->where('p.is_active = ?', true)
      ->where('p.topic_id = ?', $this->id)
      ->count()
    ;
  }
  public function getNbViews() {
    return Doctrine::getTable('DmForumTopicView')
      ->createQuery('v')
      ->where('v.topic_id = ?', $this->id)
      ->count()
    ;
  }

  public function getLastPost() {
    return Doctrine::getTable('DmForumPost')
      ->createQuery('p')
      ->select('p.*, u.username')
      ->leftJoin('p.User u')
      ->where('p.is_active = ?', true)
      ->where('p.topic_id = ?', $this->id)
      ->orderBy('p.created_at')
      ->fetchOne()
    ;
  }
  public function getLastUpdatedPost() {
    return Doctrine::getTable('DmForumPost')
      ->createQuery('p')
      ->select('p.*, u.username')
      ->leftJoin('p.User u')
      ->where('p.is_active = ?', true)
      ->where('p.topic_id = ?', $this->id)
      ->orderBy('p.updated_at')
      ->fetchOne()
    ;
  }
}