<?php

/**
 * PluginDmForumBoardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginDmForumBoardTable extends myDoctrineTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginDmForumBoardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginDmForumBoard');
    }
}