all:

  stylesheets:
    - /dmForumPlugin/css/stylesheet.css

  javascripts:
    - /dmCorePlugin/lib/jquery/jquery-1.4.2.min.js
    - /dmCorePlugin/lib/form/jquery.form.hack.js
    - /dmForumPlugin/js/dmForum.js
