generator:
  class: dmAdminDoctrineGenerator
  param:
    model_class: DmForumBoard
    theme: dmAdmin
    non_verbose_templates: true
    with_show: false
    route_prefix: board
    with_doctrine_route: false
    config:
      actions: ~
      fields:
        is_active:
          label: Active
      list:
        display:
          - '=name'
          - forums_list
          - description
          - is_active
          - created_at
          - updated_at
          - slug
        sort:
          - created_at
          - desc
        table_method: getAdminListQuery
        table_count_method: ~
        sortable: false
      filter:
        display:
          - name
          - is_active
          - description
          - created_at
          - updated_at
          - slug
      form:
        display:
          NONE: [name, is_active]
          Forums: [forums_list]
          Others: [description, slug]
        class: DmForumBoardAdminForm
        fields: {  }
      edit: ~
      new: ~
