DmForumBoard:
  actAs:
    Timestampable:
    Sluggable:
      fields: [ name ]
  columns:
    name:
      type: string
      length: 255
      notnull: true
    description:
      type: string
      extra: markdown
    is_active:
      type: boolean
      default: 1

DmForumForum:
  actAs:
    Timestampable:
    Sluggable:
      fields: [ name ]
    NestedSet:
      hasManyRoots: true
    DmSortable:
    DmBlameable:
  columns:
    name:          
      type: string
      length: 255
      notnull: true
    description:
      type: string
      extra: markdown
    is_active:
      type: boolean
      default: 1
    show_description:
      type: boolean
      default: 1
    board_id:
      type: integer
      notnull: true
    image_id:
      type: integer
  relations:
    Board:
      class: DmForumBoard
      local: board_id
      foreignAlias: Forums
      onDelete: CASCADE
    Image:
      class: DmMedia
      local: image_id
      foreignAlias: Forums
      onDelete: RESTRICT


DmForumTopic:
  actAs:
    Timestampable:
    Sluggable:
      fields: [ title ]
    DmBlameable:
    DmVersionable:
    DmTaggable:
  columns:
    title:
      type: string
      length: 255
      notnull: true
    is_active:
      type: boolean
      default: 1
    is_sticked:
      type: boolean
      default: 0
    is_locked:     
      type: boolean
      default: 0
    is_approved:
      type: boolean
      default: 0
    forum_id:
      type: integer
      notnull: true
    user_id:
      type: integer
  relations:
    Forum:
      class: DmForumForum
      local: forum_id
      foreignAlias: Topics
      onDelete: CASCADE

DmForumPost:
  actAs:
    Timestampable:
    DmBlameable:
    DmVersionable:
    DmTaggable:
  columns:
    title:
      type: string
      length: 255
    content:
      type: string
      notnull: true
      extra: markdown
    is_active:
      type: boolean
      default: 1
    is_approved:
      type: boolean
      default: 0
    topic_id:
      type: integer
      notnull: true
  relations:
    Topic:
      class: DmForumTopic
      local: topic_id
      foreignAlias: Posts
      onDelete: CASCADE

DmForumTopicView:
  actAs:
    Timestampable:
  columns:
    user_id:
      type: integer
      primary: true
    topic_id:
      type: integer
      primary: true
  relations:
    Topic:
      class: DmForumTopic
      local: topic_id
      foreignAlias: Posts
      onDelete: CASCADE
    User:
      class: DmUser
      local: user_id
      foreignAlias: Posts
      onDelete: CASCADE

